spring.application.name=screenmatch
# Allows the application to read ".env" files
spring.config.import=optional:file:.env[.properties]
spring.datasource.url=jdbc:postgresql://localhost/screenmatch_series
spring.datasource.username=${POSTGRES_USERNAME}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
hibernate.dialect=org.hibernate.dialect.HSQLDialect

spring.jpa.hibernate.ddl-auto=update